### ISSUE TITLE
Question about the mod development.

### ISSUE THREAD

**Issue by YuriGen2423** [SrGnis/Creeper_AI_Updated#24]
Just wanting to know if the mod still gonna be updated, or is it abandoned?

**Comment by SrGnis** [comment]
Hello @YuriGen2423 thanks to you and to all who have been interested in this mod.

 Yes, I am going to abandon this mod.

Lately I have not had time to continue with the Minecraft modding, and the little time I have I want to use it for other projects.

Although this was my first Minecraft mod and I have a special affection for it, I have been losing the motivation to work on it. So the most sensible thing to do is officially announce that this project is abandoned.

I have updated the mod to versions 1.19.4 and 1.20.1 but only for Fabric, it has been a long time since I stopped developing in Forge and when trying to update it has given me problems, so I have only been able to update the mod in Fabric.

This repository will be kept open until August in case there is any bug report and it will be archived later.

If someone is interested in continuing to develop this mod, do not hesitate to contact me.
